# For more details, read this: https://coolify.io/docs/github-actions
name: Production Deploy
on:
  pull_request:
    branches: [main]
    types: [closed]
  push:
    tags:
      - 'prod-*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'andrasbacsai/github-actions-with-coolify'

jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_RESOURCE_ID }}&force=false' \
           --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
